### ISSUE TITLE
Rapid project

### ISSUE THREAD

**Issue by alialameri123** [RapidProjectH2020/rapid-android-DemoApp#1]
Hi;
I am trying to install the rapid project. 
First, I did clone the rapid project and the rapid demo android application in Android Studio.
Then, I connect my Android tablet to the Android Studio and install the demo application on the Table.
After that, I imported the Andriod-X86 on a VMBox installed on my desktop.
Now, when I try to connect my Tablet to the VM using internet setting as NAT it fields and My tablet cannot ping the VM as both IP addresses have different range.
When I change the network setting to the network bridge, Both the VM and the Tablet have same IP range and they can ping each other but when I open my android tablet and lunch the rapid application and put the VM IP address, it is not connected and always shows the red light and says not Connected to VM.
I've notice one thing and it might be the case, in the installation guide, it says when you lunch the VM image the AS will start automatically? it is not starting? So is that the case? and I did not understand how it will work automatically, is it because you embedded the AS in the Android image since it is recommended to download from rapid?
could you please advise on this issue?
Your kind respond is highly appreciated
Ali

**Comment by sokol-kosta** [comment]
I am currently out of office. I will be back to you in about one week.

BR.

**Comment by alialameri123** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hi;
Thank you for your kind reply, I will be waiting to hear from you.
Kind regards;
Ali 


Sent from Yahoo Mail for iPhone

**Comment by sokol-kosta** [comment]
Hi,

First of all, as you noticed, to avoid network issues I would recommend you to use bridged networking so that the phone and the VM can ping each other. If this is the case, then you can proceed with the rest of the guide.

> I've notice one thing and it might be the case, in the installation guide, it says when you lunch the VM image the AS will start automatically? it is not starting? So is that the case? and I did not understand how it will work automatically, is it because you embedded the AS in the Android image since it is recommended to download from rapid?

Yes, this is the case. We have embedded the AS in the VM image we are distributing on the RAPID website. However, I would recommend you to clone the rapid-as project (https://github.com/RapidProjectH2020/rapid-android) so you can install the latest version of the AS on the VM yourself.

Then, you can just proceed with the rapid-demo app on the phone as you are doing now. I think you maybe are facing problems due to the fact that the AS version in the VM image maybe an older version than the rapid-demo app.

Please, try this and if you are still having problems do not hesitate to ask. To help me better understand the problem you can also paste the log of the phone and/or that of the VM here.

**Comment by alialameri123** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }      Dear Sokol;
I hope my email finds you well and thanks a lot for your kind email, and sorry for my late reply because I have a conference here in Singapore.
I've tried to change the network setting to network bridge and both phone and VM were able to ping each other but still I cannot connect to the VM.
Also when I start the Android image on the VM, the AS didn't start so I guess the problem is there. But as you said, when I am back to London I will try to clone it from the link you suggested earlier and see what is going on. So, do I need to clone it on the VM or on the Android image?
Thanks again and best wishes;
Ali

**Comment by sokol-kosta** [comment]
Hi,

You need to clone the github project on your development laptop and install
the rapid-as project on the VM.
Then, start the rapid-demo on the phone.

Best,
Sokol

**Comment by alialameri123** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hi;
So you mean I have to use Andriod Studio or Eclipse to install the rapid-as project on the VM?
Kind regards; 
Ali


Sent from Yahoo Mail for iPhone

**Comment by sokol-kosta** [comment]
Yes, that would give you the flexibility of looking what is happening.
If you don't want to do that, I am now preparing new versions of the
VirtualBox VM image so you can download that one.

BR,
Sokol

**Comment by alialameri123** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hi;
Yes please because I am not really familiar with Eclipse, so I would prefer if you could give me the new version?
Kind regards;
Ali


Sent from Yahoo Mail for iPhone

**Comment by sokol-kosta** [comment]
Hi, please try the new VM image. I tested it on two different computers and is working. The AS is indeed started automatically and is listening for devices to connect. I think it may only be an issue with networking.
Please make sure that the device can ping the VM **and** the VM can ping the device.

If you are still having problems, I also created an image with Android-x86 4.4 (read the updated instructions here: https://github.com/RapidProjectH2020/rapid-android-DemoApp). Try using that instead of the Android-x86 6.0.

Best,
Sokol

**Comment by alialameri123** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Dear Sokol;
Thanks a lot for your kind email and I hope you are doing well.
Okey that's great, I will try that once I am back and I will keep you posted.
Thanks again and best wishes;
Ali

**Comment by alialameri123** [comment]
Dear Sokol;
I hope my email finds you well.I just downloaded the new VM image version and Imported it in the VM Box, Now I can see Rapid-Server icon.
However, when I started the Rapid-server icon, nothing happened? then when I connected from the Rapid demo app on my tablet to the VM, it is connected this time and the light turns green and it says connected to the VM :))

But when I press the solve queens button, immediately it turns red and it says not connected to VM, So, is that okay? and does the Rapid-server needs to show something on it or it is just a black screen as I am seeing now? and why when I pressed the solve queens button, it turns to not connected again?Please advise??
Kind regards;
ALI

**Comment by sokol-kosta** [comment]
Hi,

Great, now it means that the app is connected with the AS. On the VM we do
not print anything, only if you visualize the log you can see what is
happening.
It is strange that when you try to solve Nqueens the connection drops. Can
you see the log of the phone? That could help me understand what is the
problem.

Best,
Sokol

**Comment by alialameri123** [comment]
Hi;
Yes, it is connected. But I think when I connect I need to see the remote results, right now I am just able to see the local results, even I tried to choose different options remote only and local only but it stills drop.What do you mean by the log of the tablet?
Kind regards;
ALI

**Comment by sokol-kosta** [comment]
From the IDE that you are using for installing the rapid-demo on the tablet
you can see the log of the tablet.
Have a look here please:
https://developer.android.com/studio/debug/am-logcat.html

**Comment by alialameri123** [comment]
Dear Sokol;
Yes, I can see the logcat of the tablet in the Andriod Studio, but it is many logs keep coming?
Kind regards;
ALI

**Comment by alialameri123** [comment]
Dear Sokol;
When I choose the eu.project.demo in the debuggable section, I can see only logs in regards to the Rapid App only. However, when I choose Error instead of Verbose, the logs show as follow:
 08-31 10:45:08.410 13824-14542/eu.project.rapid.demo E/DFE-TaskRunner-2: REMOTE ERROR: localSolveNQueens: javax.net.ssl.SSLException: Read error: ssl=0xa023c000: I/O error during system call, No route to host
08-31 10:46:47.322 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: IOException - SSL Connection setup to server failed: java.net.NoRouteToHostException: No route to host
08-31 10:46:50.328 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Connection setup with the VM failed - java.net.NoRouteToHostException: No route to host
08-31 10:46:50.329 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Could not register with the VM
08-31 10:48:53.343 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: IOException - SSL Connection setup to server failed: java.net.NoRouteToHostException: No route to host
08-31 10:48:56.345 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Connection setup with the VM failed - java.net.NoRouteToHostException: No route to host
08-31 10:48:56.345 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Could not register with the VM
08-31 10:50:59.383 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: IOException - SSL Connection setup to server failed: java.net.NoRouteToHostException: No route to host
08-31 10:51:02.383 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Connection setup with the VM failed - java.net.NoRouteToHostException: No route to host
08-31 10:51:02.383 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Could not register with the VM
08-31 10:53:05.412 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: IOException - SSL Connection setup to server failed: java.net.NoRouteToHostException: No route to host
08-31 10:53:08.417 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Connection setup with the VM failed - java.net.NoRouteToHostException: No route to host
08-31 10:53:08.418 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Could not register with the VM
08-31 10:55:11.437 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: IOException - SSL Connection setup to server failed: java.net.NoRouteToHostException: No route to host
08-31 10:55:14.438 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Connection setup with the VM failed - java.net.NoRouteToHostException: No route to host
08-31 10:55:14.438 13824-14547/eu.project.rapid.demo E/DFE-TaskRunner-2: Could not register with the VM

Does that help?
Kind regards;
ALI

**Comment by sokol-kosta** [comment]
This is helpful indeed.
Can you try selecting Clear connection instead off ssl?

Best,
Sokol

**Comment by alialameri123** [comment]
Hi;
It is the same thing, it drops once I select any of the 3 Apps??
Kind regards;
ALI

**Comment by sokol-kosta** [comment]
Can you show me the content of the file: build.gradle (Module:
rapidDemoApp) please?
And can you also paste the whole log of the tablet for the rapidDemoApp
(not only the error ones)?

Thanks.

**Comment by alialameri123** [comment]
Hi;That is the content of the build.gradle(Module: rapidDemoApp):
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "eu.project.rapid.demo"
        minSdkVersion 19
        targetSdkVersion 25

        ndk {
            moduleName "hello-jni"
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
        release {
            minifyEnabled false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    // The libraries are imported in settings.gradle when developing locally.
    // Uncomment the following lines if you are just a user.
    //    compile 'eu.project.rapid:rapid-android-ac:0.0.9'
    //    compile 'eu.project.rapid:rapid-gvirtus4a:0.0.2'
    compile project(':rapid-android-ac')
    compile project(':rapid-gvirtus4a')
    compile files('libs/core-1.51.0.0.jar')
    compile files('libs/prov-1.51.0.0.jar')
}

**Comment by sokol-kosta** [comment]
Great, thanks. Can you also include in the log the part when you try to
offload something and it crashes?

**Comment by alialameri123** [comment]
Hi;

**Comment by sokol-kosta** [comment]
From this log it looks like it couldn't connect...

**Comment by alialameri123** [comment]
Hi;
Yes, in the beginning, it couldn't connect for three times but after that, it is connected successfully and it shows the green command connect to VM in SSL, then when I choose 4 or 5 queens, it immediately disconnects and says in red not connected to VM and it shows just the local results.

Kind regards;
ALI
 

    On Thursday, August 31, 2017 3:08 PM, Sokol Kosta <notifications@github.com> wrote:
 

 From this log it looks like it couldn't connect...—

**Comment by sokol-kosta** [comment]
Ok, can you show me the log when that happens? (when you try to offload and it disconnects).

**Comment by alialameri123** [comment]
Hi;
If you go through the log, you can see part of it where I highlighted it with green, I think it was unable to connect. But in the last part of the log where I highlighted it with red, I think it says connection completed and socket created? please have a look?

**Comment by alialameri123** [comment]
Dear Sokol;
I hope my email finds you well and I would like to thank you for your kind support.I am sorry that I am asking so many questions and I know your time is valuable but honestly speaking your kind reply and information help me a lot.
In regards to my last email, any updates on the following?
Kind regards;
ALI

**Comment by sokol-kosta** [comment]
Hi,

Please let me know tomorrow, September 7, when you can perform a test so I
can create a VM for you on the Amazon cloud.
That way we can test and see if the issue is with your networking
configuration.

Please contact me in private using my email so I can give you the
credential access to the VM.

Best Regards,
Sokol

**Comment by alialameri123** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hi Sokol;
Thanks for getting back to me. Yes tomorrow from 10:00 am to 12:00 pm, I can perform a test.Could you please give me your personal email so I can contact you?
Kind regards;
Ali


Sent from Yahoo Mail for iPhone

**Comment by sokol-kosta** [comment]
Great, let's talk around that time. Send me an email to kosta[at]
di.uniroma1.it

BR
Sokol

**Comment by alialameri123** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Okey sure will do.
Best wishes;
Ali


Sent from Yahoo Mail for iPhone


On Wednesday, September 6, 2017, 5:54 PM, Sokol Kosta <notifications@github.com> wrote:

Great, let's talk around that time. Send me an email to kosta[at]
di.uniroma1.it

BR
Sokol

**Comment by alialameri123** [comment]
Dear Sokol;
I hope you are doing well and I would like to thank you once again for your promote support indeed.
I just wanted to let you know that the problem has been solved and I am able to communicate between the tablet and the VM and I can see now both local and remote results :). I am very interested in the Rapid project and definitely, I am keen to learn and know more details from you guys.
Special thanks for Mr Sokol for his kind notes, help and support, Without his help, the problems might never be solved.
Kind regards;
ALI AL-AMERI
