### ISSUE TITLE
busybox ifconfig always returns localhost

### ISSUE THREAD

**Issue by talha89** [RapidProjectH2020/rapid-android-DemoApp#2]
While trying to get the IP address of the VM using 'busybox ifconfig' as mentioned in the guide it always gives me the local address (127.0.0.1) and not the IP of the machine. Tried other commands as well, same problem. 
I'm using Oracle's VirtualBox v5.1.22 on Windows 10.

**Comment by sokol-kosta** [comment]
Hi,

I am sure you have not configured networking properly. You should choose bridged networking, not NAT.
Please refer to Virtualbox tutorials on how to configure networking.

BR.

**Comment by talha89** [comment]
Hi, 

I tried Bridged Networking as well, it gives the same result. No matter what the networking mode is, it always returns the local address.

**Comment by sokol-kosta** [comment]
I am sorry. This issue is not related to RAPID, is a matter of network configuration.
Please try to read the VirtualBox guidelines on how to do this.

BR.
